function vec=btc_corrs2vec(corrs,dict)
% vec=btc_corrs2vec(corrs,dict) converts a structure of correlations with
% field names gamma, beta, theta, alpha to a vector
%
% corrs:  a structure with fields gamma, beta, theta, alpha.
% dict:  dictionary of binary correlation names, generated by btc_define;
%    btc_define called if this field is empty
%
% vec: a 10-vector, typically a row
%
%    See also: BTC_DEFINE, BTC_VEC2CORRS, BTC_VEC2LETCODE, BTC_LETCODE2VEC, GETP2X2_CORRS, GETCORRS_P2X2.
%
if (nargin<2)
    dict=btc_define;
end
vec=zeros(1,length(dict.codel));
for k=1:length(dict.codel)
%    vec(k)=getfield(corrs,dict.name_order{k},{dict.posit(k)});
    vec(k)=corrs.(dict.name_order{k})(1,dict.posit(k));
end
return
